npmAlwaysAuth: true

npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@emotion/babel-plugin@*':
    dependencies:
      '@babel/core': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-berry.cjs
